# Generated by Django 3.2 on 2021-04-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Обязательное поле', max_length=255, verbose_name='Заголовок')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключевые слова')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slide_photo_heading_text', models.CharField(blank=True, max_length=255, verbose_name='Заголовок над слайдером')),
                ('slide_photo_bottom_text', models.TextField(blank=True, verbose_name='Текст под слайдером')),
                ('product_heading_text', models.CharField(blank=True, max_length=255, verbose_name='Заголовок продуктов')),
                ('map_latitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Широта')),
                ('map_longitude', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Долгота')),
                ('feedback_form_title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок формы фидбека')),
            ],
        ),
    ]
