# Generated by Django 3.2 on 2021-04-24 11:21

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import working_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('working_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'данные', 'verbose_name_plural': 'Главная страница'},
        ),
        migrations.CreateModel(
            name='HomePageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, keep_meta=True, quality=0, size=[1280, 860], upload_to=working_app.models.get_image_path, verbose_name='Фото для слайдера')),
                ('homepage', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='working_app.homepage', verbose_name='Картинка для слайдера')),
            ],
        ),
    ]
