# Generated by Django 3.2 on 2021-04-24 13:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('working_app', '0003_auto_20210424_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Обязательное поле', max_length=255, verbose_name='Название продукта')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключевые слова')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, help_text='Допускаются только изображения в формате .jpg, .jpeg', keep_meta=True, quality=80, size=[1280, 860], upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])], verbose_name='Фото продукта')),
                ('heading', models.CharField(help_text='Обязательное поле', max_length=255, verbose_name='Заголовок продукта')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format=None, help_text='Допускаются только изображения в формате .jpg, .jpeg', keep_meta=True, quality=80, size=[1280, 860], upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])], verbose_name='Фото для слайдера'),
        ),
        migrations.CreateModel(
            name='ProductHeadingParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Обязательное поле', verbose_name='Содержание пункта')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_paragraph', to='working_app.product', verbose_name='Пункт списка')),
            ],
            options={
                'verbose_name': 'пункт',
                'verbose_name_plural': 'пункты',
            },
        ),
    ]
