# Generated by Django 3.2 on 2021-04-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('working_app', '0004_auto_20210424_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='heading',
        ),
        migrations.AddField(
            model_name='product',
            name='heading1',
            field=models.CharField(blank=True, help_text='Обязательное поле', max_length=255, verbose_name='Заголовок продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='heading2',
            field=models.CharField(blank=True, help_text='Обязательное поле', max_length=255, verbose_name='Заголовок продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='heading3',
            field=models.CharField(blank=True, help_text='Обязательное поле', max_length=255, verbose_name='Заголовок продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='text1',
            field=models.TextField(blank=True, help_text='Обязательное поле', verbose_name='Содержание пункта 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='text2',
            field=models.TextField(blank=True, help_text='Обязательное поле', verbose_name='Содержание пункта 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='text3',
            field=models.TextField(blank=True, help_text='Обязательное поле', verbose_name='Содержание пункта 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='продукт', help_text='Обязательное поле', max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductHeadingParagraph',
        ),
    ]
