# Generated by Django 3.2 on 2021-04-24 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('working_app', '0005_auto_20210424_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_pub'], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='heading1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='heading2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='heading3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text1',
            field=models.TextField(blank=True, verbose_name='Содержание пункта 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text2',
            field=models.TextField(blank=True, verbose_name='Содержание пункта 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text3',
            field=models.TextField(blank=True, verbose_name='Содержание пункта 3'),
        ),
    ]
